# Generated by Django 5.1.4 on 2026-03-21 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_etap3_booking_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('processed', models.BooleanField(default=False)),
                ('payload_summary', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Webhook Stripe',
                'verbose_name_plural': 'Webhooki Stripe',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('guests_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca (prośba do hosta)'), ('awaiting_payment', 'Oczekuje płatności'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana'), ('rejected', 'Odrzucona'), ('completed', 'Zakończona'), ('abandoned', 'Porzucona (brak płatności)'), ('payment_failed', 'Płatność nieudana')], db_index=True, default='pending', max_length=32)),
                ('pricing_breakdown', models.JSONField()),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('host_response_deadline', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia statusu rezerwacji',
                'verbose_name_plural': 'Historie statusów rezerwacji',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('succeeded', 'Zaksięgowana'), ('failed', 'Nieudana')], default='pending', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('provider_payment_id', models.CharField(help_text='Unikalny identyfikator Stripe (np. payment_intent) — idempotencja webhook.', max_length=255, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Zablokowany dzień',
                'verbose_name_plural': 'Zablokowane dni',
                'indexes': [models.Index(fields=['listing_id', 'date'], name='bookings_bl_listing_d7d495_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('listing', 'date'), name='bookings_blockeddate_listing_date_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing_id', 'check_in', 'check_out'], name='bookings_bo_listing_483dae_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest_id', 'status'], name='bookings_bo_guest_i_261eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_checkout_after_checkin'),
        ),
    ]
