# Generated by Django 5.1.4 on 2026-03-21 14:57

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('booking_mode', models.CharField(choices=[('instant', 'Natychmiastowa'), ('request', 'Na prośbę')], default='instant', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('pending', 'Oczekuje na moderację'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona'), ('archived', 'Zarchiwizowana')], db_index=True, default='draft', max_length=20)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='host.hostprofile')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Oferty',
            },
        ),
        migrations.CreateModel(
            name='ListingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='PL', max_length=2)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Lokalizacja oferty',
                'verbose_name_plural': 'Lokalizacje ofert',
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='listings_li_status_29a9da_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['host_id', 'status'], name='listings_li_host_id_0cc27d_idx'),
        ),
        migrations.AddIndex(
            model_name='listinglocation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['point'], name='listings_li_point_345b0a_gist'),
        ),
    ]
