# Generated by Django 5.1.4 on 2026-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listinglocation_point_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opłata sprzątająca (jednorazowo).', max_digits=10),
        ),
    ]
