# Generated by Django 5.1.4 on 2026-03-21 18:50

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_etap3_rich_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingreview',
            new_name='listings_li_listing_3c234c_idx',
            old_name='listings_li_listing_6e1c0e_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.JSONField(default=apps.listings.models.default_listing_type),
        ),
    ]
