# Generated by Django 5.1.4 on 2026-03-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_listings_li_listing_6e1c0e_idx_listings_li_listing_3c234c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Uzasadnienie moderacji (np. powód odrzucenia).'),
        ),
    ]
