#!/bin/bash
# AI Search Quick Manual Test Script
# Testuj AI Search bez Dockera — jeśli masz DB PostGIS

set -e

echo "=== AI Search Manual Testing ==="
echo ""
echo "1. SETUP"
echo "   Wymaga:"
echo "   - PostgreSQL z PostGIS"
echo "   - Python 3.11+, Node 18+"
echo "   - Env var: OPENAI_API_KEY (nowy, unieważniony stary)"
echo ""
echo "2. URUCHAMIANIE"
echo ""
echo "   # Terminal 1 — Backend"
echo "   cd backend"
echo "   export DJANGO_SETTINGS_MODULE=config.settings.development"
echo "   python manage.py runserver"
echo ""
echo "   # Terminal 2 — Frontend"
echo "   cd frontend"
echo "   npm run dev"
echo ""
echo "3. TEST CASES"
echo ""
echo "   # Test 1: Podstawowy prompt"
echo "   curl -X POST http://localhost:8000/api/v1/ai/search/ \\"
echo "     -H 'Authorization: Bearer YOUR_ACCESS_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"prompt\": \"Domek z sauną dla dwojga na Mazurach\"}'"
echo ""
echo "   # Test 2: Kontynuacja sesji (follow-up)"
echo "   curl -X POST http://localhost:8000/api/v1/ai/search/ \\"
echo "     -H 'Authorization: Bearer YOUR_ACCESS_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"prompt\": \"Dodaj miejsca nad jeziorem\", \"session_id\": \"UUID_Z_TEST_1\"}'"
echo ""
echo "   # Test 3: Status sesji"
echo "   curl -X GET http://localhost:8000/api/v1/ai/search/{SESSION_ID}/ \\"
echo "     -H 'Authorization: Bearer YOUR_ACCESS_TOKEN'"
echo ""
echo "4. OCZEKIWANE RESPONSE (Test 1)"
echo ""
echo "   {"
echo "     \"data\": {"
echo "       \"session_id\": \"...\","
echo "       \"status\": \"complete\","
echo "       \"assistant_reply\": \"Przygotowałem romantyczne domki...\","
echo "       \"follow_up_suggestions\": [\"Pokaż luksusowe opcje\", ...,"
echo "       \"conversation\": ["
echo "         {\"role\": \"user\", \"text\": \"Domek z sauną...\", \"created_at\": \"...\"},"
echo "         {\"role\": \"assistant\", \"text\": \"Przygotowałem...\", \"created_at\": \"...\"}"
echo "       ],"
echo "       \"model_used\": \"gpt-4o-mini\","
echo "       \"tokens_used\": 123,"
echo "       \"cost_usd\": 0.00015,"
echo "       \"results\": ["
echo "         {\"listing_id\": \"...\", \"title\": \"...\", \"match_score\": 95, ...}"
echo "       ]"
echo "     }"
echo "   }"
echo ""
echo "5. FRONTEND TEST (http://localhost:3000/ai)"
echo ""
echo "   ✓ Textarea input pojawia się"
echo "   ✓ Quick prompts chips (Weekend wellness, Romantyczny domek, etc.)"
echo "   ✓ Klik 'Szukaj' wysyła POST /api/v1/ai/search/"
echo "   ✓ Status zmienia się: pending → processing → complete"
echo "   ✓ Pojawia się sekcja wyników (24 karty)"
echo "   ✓ AI Pick badge + dopasowanie % (100 - rank*2)"
echo "   ✓ Panel czatu (AIChatPanel):"
echo "     - Historia rozmowy (user + assistant messages)"
echo "     - Assistant reply (podsumowanie)"
echo "     - Follow-up suggestions (klinkable chips)"
echo "   ✓ Klik na suggestion → wysłanie w tej samej sesji (session_id)"
echo "   ✓ Conversation rozszerza się"
echo ""
echo "6. MONITORING"
echo ""
echo "   - Backend logs: szukaj \"AISearchService.run_sync\" + model_used"
echo "   - Frontend Network tab: POST /api/v1/ai/search/ + session_id"
echo "   - Response time: ~3-8s (LLM call + search)"
echo ""
echo "7. THROTTLE TEST"
echo ""
echo "   - Wyślij 21 żądań w ciągu 60 sekund"
echo "   - Oczekiwane: 429 Too Many Requests (ai_search: 20/min)"
echo ""
echo "=== GOTÓW DO TESTOWANIA ==="

