# Generated by Django 5.1.4 on 2026-03-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_action_ead800_idx',
            old_name='common_audit_action_c9c8c3_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='common_audi_object__a9d982_idx',
            old_name='common_audit_object_e4b2f8_idx',
        ),
    ]
