# Generated by Django 5.1.4 on 2026-03-21 16:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_etap3_booking_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongStayDiscountRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_nights', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_stay_rules', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Rabat długiego pobytu',
                'verbose_name_plural': 'Rabaty długiego pobytu',
                'ordering': ['-min_nights', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('valid_from', models.DateField(db_index=True)),
                ('valid_to', models.DateField(db_index=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rules', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Reguła sezonowa',
                'verbose_name_plural': 'Reguły sezonowe',
                'ordering': ['-priority', '-multiplier'],
            },
        ),
        migrations.CreateModel(
            name='CustomDatePrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('price_override', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_date_prices', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Cena dzienna',
                'verbose_name_plural': 'Ceny dzienne',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('listing', 'date'), name='pricing_customdateprice_listing_date_uniq')],
            },
        ),
        migrations.CreateModel(
            name='HolidayPricingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_rules', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Reguła świąteczna',
                'verbose_name_plural': 'Reguły świąteczne',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('listing', 'date'), name='pricing_holidayrule_listing_date_uniq')],
            },
        ),
    ]
