# Generated by Django 5.1.4 on 2026-03-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_airecommendation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aitravelsession',
            new_name='ai_assistan_user_id_95bf3f_idx',
            old_name='ai_assistant_user_id_0f8b2d_idx',
        ),
    ]
