# Generated by Django 5.1.4 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0003_rename_ai_assistant_user_id_0f8b2d_idx_ai_assistan_user_id_95bf3f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="airecommendation",
            name="match_explanation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="match_highlights",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="airecommendation",
            name="explanation_source",
            field=models.CharField(blank=True, default="rule", max_length=16),
        ),
    ]

