# Generated by Django 5.1.4 on 2026-03-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wishlist_savedsearch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='users_wishl_user_id_4d9d99_idx',
            old_name='users_wishlist_user_created_idx',
        ),
    ]
