# Generated by Django 5.1.4 on 2026-03-21 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_guest_details'),
        ('listings', '0007_etap6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_role', models.CharField(choices=[('guest', 'Gość o pobycie'), ('host', 'Host o gościu')], db_index=True, default='guest', max_length=16)),
                ('author_display_first', models.CharField(blank=True, max_length=80)),
                ('author_display_last', models.CharField(blank=True, max_length=80)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('subscores', models.JSONField(blank=True, help_text='np. {"cleanliness":4.5,"location":5,"communication":4.5,"accuracy":5}', null=True)),
                ('blind_release_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_blind_review_released', models.BooleanField(default=False)),
                ('host_response', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_reviews', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stay_reviews', to='bookings.booking')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_reviews', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Recenzja',
                'verbose_name_plural': 'Recenzje',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_id', 'is_public', 'created_at'], name='reviews_rev_listing_0a69b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('booking__isnull', False), ('deleted_at__isnull', True)), fields=('booking', 'reviewer_role'), name='reviews_review_booking_role_uniq')],
            },
        ),
    ]
